version: '3.4'

services:

  memberDb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  membership.api:
    image: ${DOCKER_REGISTRY-}membershipapi
    build:
      context: .
      dockerfile: API/Membership/Membership.API/Dockerfile
  
  healthdata.api:
    image: ${DOCKER_REGISTRY-}healthdataapi
    build:
        context: .
        dockerfile: API/HealthData/HealthData.API/Dockerfile

  membership-spa:
    image: ${DOCKER_REGISTRY-}membership-spa
    build:
      context: .
      dockerfile: membership-spa/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management-alpine
